manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import:
        path: app/west.yml
        # zmk側の定義からpmw3610を除外し、自分の定義を優先させる
        name-blocklist:
          - zmk-pmw3610-driver
    - name: zmk-pmw3610-driver
      remote: urob
      revision: main
  self:
    path: config