CONFIG_ZMK_KEYBOARD_NAME="roBa"

CONFIG_ZMK_POINTING=y
CONFIG_NFCT_PINS_AS_GPIOS=y
CONFIG_ZMK_BLE=y



CONFIG_SPI=y
CONFIG_INPUT=y

CONFIGZMK_INPUT_PMW3610=y
CONFIGZMK_INPUT_PMW3610_CPI=400
CONFIGZMK_INPUT_PMW3610_CPI_DIVIDOR=1
CONFIGZMK_INPUT_PMW3610_ORIENTATION_180=y
# CONFIGZMK_INPUT_PMW3610_SNIPE_CPI=800
# CONFIGZMK_INPUT_PMW3610_SNIPE_CPI_DIVIDOR=4
CONFIGZMK_INPUT_PMW3610_SCROLL_TICK=16
CONFIGZMK_INPUT_PMW3610_INVERT_X=n
CONFIGZMK_INPUT_PMW3610_INVERT_SCROLL_X=y
CONFIGZMK_INPUT_PMW3610_RUN_DOWNSHIFT_TIME_MS=3264
CONFIGZMK_INPUT_PMW3610_REST1_SAMPLE_TIME_MS=20
#CONFIGZMK_INPUT_PMW3610_REST1_DOWNSHIFT_TIME_MS=9600
#CONFIGZMK_INPUT_PMW3610_REST2_SAMPLE_TIME_MS=
#CONFIGZMK_INPUT_PMW3610_REST2_DOWNSHIFT_TIME_MS=
#CONFIGZMK_INPUT_PMW3610_REST3_SAMPLE_TIME_MS=
#CONFIGZMK_INPUT_PMW3610_REST3_DOWNSHIFT_TIME_MS=
#CONFIGZMK_INPUT_PMW3610_FORCE_AWAKE=n
CONFIGZMK_INPUT_PMW3610_POLLING_RATE_125_SW=y
CONFIGZMK_INPUT_PMW3610_AUTOMOUSE_TIMEOUT_MS=700

CONFIGZMK_INPUT_PMW3610_MOVEMENT_THRESHOLD=0

CONFIGZMK_INPUT_PMW3610_SMART_ALGORITHM=y

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n 

